name: IdeaGenerator
version: 1.0.0
author: SciDev
api-version: 1.16
main: me.scidev.spigotIdeaGenerator.Main
commands:
   idea:
      description: "Come up with a brilliant idea."
permissions:
   spigotIdeaGenerator.commands.*:
      default: true
      children:
         spigotIdeaGenerator.commands.idea.use: true
   spigotIdeaGenerator.commands.idea.use:
      default: true
